# Site settings
title: "Vineet Kulkarni"
email: vineet.kulkarni8@gmail.com
description: "Software Engineer."
baseurl: ""
url: "http://kvineet.github.io/"
title_description: "I am a Software Engineer. I have worked as Java developer for more that 4 years, experience in web applications, REST APIs and micro service architecture. My complete profile can be found in <a href=\"about\">About Me</a> page."
title_image: "https://farm9.staticflickr.com/8554/29762891402_db4ce49313_z.jpg"
google_analytics: "UA-84651125-1"
disqus_account: kvineet
github_repository: https://github.com/kvineet/
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: vineetkulkarni8
github_username:  kvineet
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">carte-noire</a> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "hosted on  &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
